Load balancer

diff --git a/0x0F-load_balancer/1-install_load_balancer b/0x0F-load_balancer/1-install_load_balancer
--- a/0x0F-load_balancer/1-install_load_balancer
+++ b/0x0F-load_balancer/1-install_load_balancer
@@ -6,8 +6,7 @@
 # Install and configure HAproxy on my lb-01 server.
 sudo apt-get -y update
 apt-get -y install haproxy
-
-# edit config file
+# Configure HAProxy
 server_config=\
 "
 frontend  joshua-frontend
@@ -26,3 +25,11 @@ echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
 echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
 
 sudo service haproxy restart
+
+# Test HAProxy configuration
+curl -s http://localhost:80/ | grep -q "Hello World!"
+if [ $? -eq 0 ]; then
+    echo "HAProxy installed and configured successfully!"
+else
+    echo "HAProxy configuration failed!"
+fi
